### ISSUE TITLE
Token Issue

### ISSUE THREAD

**Issue by Batuminien** [Meliksahcaliskan/Learning-Management-System#8]
The token must be added manually as a header to the APIs on the frontend. Investigations should be made to determine whether this work should be done by the backend.

**Comment by Haruncakir** [comment]
As far as my research, it is normal to send bearer token from frontend but there is a way to automatize it (response generated via chatgpt):
# Automating Token Addition in Kotlin Multiplatform Frontend

To automate the process of adding a token to API requests in your frontend (Kotlin Multiplatform), you can use several techniques and tools. Here’s how you can streamline the process:

---

## 1. Use an HTTP Client Interceptor
An **HTTP interceptor** is the most common approach to automate adding tokens to requests. In Kotlin Multiplatform, you can use `Ktor` for networking, which supports request customization.

### Example: Automating Token Injection with Ktor
```kotlin
import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.features.*
import io.ktor.client.statement.*

// Create a Ktor client with an interceptor to add the Authorization header
val client = HttpClient {
    defaultRequest {
        val token = retrieveToken()
        if (token != null) {
            headers.append("Authorization", "Bearer $token")
        }
    }
}

// Function to retrieve the token from secure storage or memory
fun retrieveToken(): String? {
    // Replace with actual token retrieval logic
    return "your_token_here"
}

// Example of making a request
suspend fun fetchProtectedResource() {
    try {
        val response: HttpResponse = client.get("https://example.com/api/protected-resource")
        println(response.readText())
    } catch (e: Exception) {
        println("Error: ${e.message}")
    }
}
```
What Happens Here:

    The defaultRequest block ensures that every request automatically includes the Authorization header with the token.

2. Securely Store the Token

To prevent repeatedly fetching the token from the server or requiring user input, store it securely. Here’s how you can manage token storage in Kotlin Multiplatform:
Use Multiplatform Libraries for Secure Storage

    Use libraries like [multiplatform-settings](https://github.com/russhwolf/multiplatform-settings) for secure and cross-platform storage of tokens.
    On Android, use EncryptedSharedPreferences or Keystore.
    On iOS, use Keychain.

Example with multiplatform-settings:
```kotlin
import com.russhwolf.settings.Settings
import com.russhwolf.settings.get

val settings: Settings = Settings()

fun saveToken(token: String) {
    settings.putString("auth_token", token)
}

fun retrieveToken(): String? {
    return settings.getStringOrNull("auth_token")
}
```
3. Handle Token Expiry and Refresh

If your backend issues tokens with expiration times, you need to detect token expiry and automatically refresh the token.
Steps:

    Add logic to detect a 401 Unauthorized response.
    Attempt to refresh the token using a refresh token (if supported by the backend).
    Retry the failed request with the new token.

Ktor Example:
```kotlin
val client = HttpClient {
    expectSuccess = false
    defaultRequest {
        val token = retrieveToken()
        if (token != null) {
            headers.append("Authorization", "Bearer $token")
        }
    }

    HttpResponseValidator {
        validateResponse { response ->
            if (response.status.value == 401) {
                val newToken = refreshToken()
                if (newToken != null) {
                    saveToken(newToken)
                    throw RetryException()
                }
            }
        }
    }
}

// Function to refresh the token
suspend fun refreshToken(): String? {
    // Call your refresh endpoint
    return "new_token_here"
}

// Custom exception to retry requests after token refresh
class RetryException : Exception()
```
4. Centralized API Service

Encapsulate all API calls in a centralized service class. This makes the token handling reusable and avoids redundant code.
Example of a Service Layer:
```kotlin
object ApiService {
    private val client = HttpClient {
        defaultRequest {
            val token = retrieveToken()
            if (token != null) {
                headers.append("Authorization", "Bearer $token")
            }
        }
    }

    suspend fun getResource(): String {
        return client.get("https://example.com/api/resource")
    }
}
```
5. Use Middleware or Wrapper Functions

If you're using Ktor, you can create wrapper functions around the HTTP client to handle token injection and refresh logic.
Example Wrapper:
```kotlin
suspend fun <T> apiCall(call: suspend HttpClient.() -> T): T {
    return try {
        client.call()
    } catch (e: RetryException) {
        apiCall(call) // Retry once after refreshing the token
    }
}
```
6. Add Retry Logic

If a request fails due to token expiration, retry the request after fetching a new token.
Example:
```kotlin
suspend fun fetchResourceWithRetry(): String? {
    try {
        return client.get("https://example.com/api/resource")
    } catch (e: RetryException) {
        return fetchResourceWithRetry() // Retry once after refreshing the token
    }
}
```

**Comment by Haruncakir** [comment]
!!! Don't forget that after access token expires, refresh token will renew it but the new access token will be different
